const source=[
 {id:'17551',property:'Villa Arindra',kind:'urgent',tag:'Inspection Update',title:'Review Critical Issues & Required Actions Now',image:'https://bigrr-storage.s3.us-east-2.amazonaws.com/8468a9cc70b88997c86973c19.png',deadline:'Hari ini · 18.00 WITA',ask:'Apakah Anda akan menindaklanjuti temuan inspeksi?',yes:"I'll change it",no:'I have question'},
 {id:'16284',property:'Romeo Beachfront Bungalow',kind:'review',tag:'Extreme Bad Reviews',title:'Alert: 1-Star Review for Romeo Beachfront Bungalow',image:'https://bigrr-storage.s3.us-east-2.amazonaws.com/c591d8c69d4adbaf03b744c3d.jpg',deadline:'Hari ini · 20.00 WITA',ask:'Apakah Anda ingin tim membantu meninjau respons review?',yes:'Ya, bantu tindak lanjuti',no:'Saya ingin diskusi'},
 {id:'17550',property:'Villa Kelana',kind:'urgent',tag:'Inspection Update',title:'Review Critical Issues & Required Actions Now',image:'https://bigrr-storage.s3.us-east-2.amazonaws.com/8468a9cc70b88997c86973c0f.png',deadline:'Besok · 12.00 WITA',ask:'Apakah Anda akan menindaklanjuti temuan inspeksi?',yes:"I'll take action",no:'I have question'},
 {id:'17549',property:'Villa Balincia',kind:'urgent',tag:'Inspection Update',title:'Review Critical Issues & Required Actions Now',image:'https://bigrr-storage.s3.us-east-2.amazonaws.com/f9761d0d0c8831898e7908103.png',deadline:'Besok · 18.00 WITA',ask:'Apakah Anda akan menindaklanjuti temuan inspeksi?',yes:"I'll take action",no:'I have question'},
 {id:'17554',property:'Kaja Asri Estate',kind:'update',tag:'Inspection Update',title:'Inspection Update — No Owner Action Required',image:'https://bigrr-storage.s3.us-east-2.amazonaws.com/86d8e68865a91ef8001c97d18.jpg',deadline:'Tidak perlu respons',ask:'',yes:'',no:''},
 {id:'17518',property:'Semua properti',kind:'update',tag:'Announcement',title:'Understand the Strategy',image:'https://bigrr-storage.s3.us-east-2.amazonaws.com/71b58f8ae5aceb88d3d5b874e.png',deadline:'Tidak perlu respons',ask:'',yes:'',no:''},
 {id:'17517',property:'Semua properti',kind:'update',tag:'Announcement',title:'Pahami Strategi Harga Masuk Akal! Kok Bisa?',image:'https://bigrr-storage.s3.us-east-2.amazonaws.com/1ba746394fc4d7bd53a2f8264.png',deadline:'Tidak perlu respons',ask:'',yes:'',no:''}
];
let state={screen:'lock',scenario:'urgent',tab:'pending',property:'all',query:'',active:null,slide:0,responses:{},toast:''};
const alertSound=new Audio('mixkit-slot-machine-win-alert-1931.wav');alertSound.preload='auto';function playNoticeSound(){alertSound.pause();alertSound.currentTime=0;if(state.scenario!=='update')alertSound.play().catch(()=>{state.toast='Tekan Putar ulang notifikasi untuk mendengar suara';render()})}
const $=s=>document.querySelector(s);const el=$('#screen');const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function selected(){return source.find(x=>x.id===state.active)}
function noticeItem(){return source.find(x=>x.kind===state.scenario)}
function lock(){let x=noticeItem();return `<div class="lock"><div class="lockdate">Rabu, 7 Oktober</div><div class="locktime">9:41</div><button class="lock-card" data-action="open-notice"><div class="lock-head"><img src="bvgo-app-icon.png" alt="BVGO"><b>BVGO</b><span>sekarang</span></div><strong>${x.kind==='update'?'Update baru':'Perlu tanggapan'} · ${esc(x.property)}</strong><small>${esc(x.title)}<br>${x.kind==='update'?'Baca kapan sempat.':'Tanggapi sebelum '+esc(x.deadline)+'. Ketuk untuk membuka Action.'}</small></button><div class="locktip">Ketuk notifikasi untuk membuka Action terkait</div></div>`}
function nav(){return `<nav class="nav"><button><span>⌂</span>Home</button><button class="active"><span>▣</span>Actions</button><button><span>▤</span>Inbox</button><button><span>◯</span>Profile</button></nav>`}
function list(){let pending=source.filter(x=>x.kind!=='update'&&!state.responses[x.id]).length;let values=[...new Set(source.filter(x=>x.property!=='Semua properti').map(x=>x.property))];let cards=source.filter(x=>(state.tab==='pending'?x.kind!=='update'&&!state.responses[x.id]:x.kind==='update'||state.responses[x.id])&&(state.property==='all'||x.property===state.property||x.property==='Semua properti')&&(`${x.title} ${x.property} ${x.tag}`.toLowerCase().includes(state.query.toLowerCase())));return `<header class="app-head"><div class="app-head-row"><img class="logo" src="bvgo.png" alt="BVGO"><img class="avatar" src="partner.jpg" alt="Foto profil partner"></div><h1 class="app-title">Actions</h1><div class="sub">Temukan keputusan penting untuk properti Anda.</div></header><div class="tabs"><button data-tab="pending" class="${state.tab==='pending'?'selected':''}">Perlu tanggapan · ${pending}</button><button data-tab="updates" class="${state.tab==='updates'?'selected':''}">Update</button></div><div class="filters"><select id="property"><option value="all">Semua properti</option>${values.map(v=>`<option value="${esc(v)}" ${state.property===v?'selected':''}>${esc(v)}</option>`).join('')}</select><input id="search" placeholder="Cari Action atau properti" value="${esc(state.query)}"></div><div class="count">${cards.length} ${state.tab==='pending'?'keputusan menunggu':'update tersedia'}</div><div class="feed">${cards.length?cards.map(x=>`<button class="card" data-open="${x.id}"><div class="card-top"><img class="thumb" src="${x.image}" alt=""><div class="card-body"><div class="meta ${x.kind==='review'?'urgent':''}">${esc(x.tag)} · ${esc(x.property)}</div><h3>${esc(x.title)}</h3><p>${x.kind==='update'?'Informasi untuk Anda':'Menunggu keputusan Anda'}</p></div></div><div class="card-bottom"><span>${esc(x.deadline)}</span><b>${x.kind==='update'?'Lihat update →':state.responses[x.id]?'Sudah ditanggapi →':'Tanggapi →'}</b></div></button>`).join(''):`<div class="empty">Tidak ada Action yang cocok.<br>Coba properti atau kata kunci lain.</div>`}</div>${nav()}`}
function detail(){let x=selected();let done=state.responses[x.id];let info=x.kind==='update';return `<div class="detail-top"><button class="back" data-action="back">‹</button><strong>${esc(x.property)}</strong></div><div class="detail-content"><span class="pill ${info?'blue':x.kind==='review'?'red':''}">${info?'Update · Tidak perlu respons':done?'Sudah ditanggapi':'Perlu tanggapan'}</span><h2>${esc(x.title)}</h2><div class="sub">${esc(x.tag)} · ${esc(x.property)}</div><img class="heroimg" src="${x.image}" alt="Konten Action BigRR" loading="lazy"><p class="imagehint">Konten visual referensi dari BigRR</p><div class="brief"><strong>${info?'Untuk diketahui':'Keputusan yang dibutuhkan'}</strong><p>${info?'Informasi ini tidak memerlukan respons owner. Anda dapat membacanya kapan sempat.':esc(x.ask)}</p></div><div class="brief"><strong>${info?'Status':'Batas respons'}</strong><p>${esc(x.deadline)}</p></div><button class="small-link" data-action="comment">Lihat / tulis komentar ↗</button><div id="comment-area"></div></div>${info?'':`<div class="response">${done?`<div class="success">✓ Respons tercatat: <b>${esc(done)}</b><br>Tim dapat menindaklanjuti jawaban Anda.</div>`:`<div class="prompt">${esc(x.ask)}</div><div class="buttons"><button data-respond="yes">${esc(x.yes)}</button><button class="alt" data-respond="no">${esc(x.no)}</button></div>`}</div>`}`}
function render(){el.innerHTML=state.screen==='lock'?lock():state.screen==='list'?list():detail();document.querySelectorAll('[data-scenario]').forEach(b=>b.classList.toggle('active',b.dataset.scenario===state.scenario));const replay=$('#replay-sound');replay.disabled=state.scenario==='update';$('#sound-caption').textContent=state.scenario==='update'?'Update biasa: tanpa suara khusus':'Suara khusus untuk inspection dan bad review';if(state.toast){let t=document.createElement('div');t.className='toast';t.textContent=state.toast;el.appendChild(t);setTimeout(()=>{t.remove();state.toast=''},2600)}}
document.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.id==='replay-sound'){playNoticeSound();return}if(b.dataset.scenario){state.scenario=b.dataset.scenario;state.screen='lock';state.active=null;render();playNoticeSound();return}if(b.id==='reset'){state={screen:'lock',scenario:'urgent',tab:'pending',property:'all',query:'',active:null,slide:0,responses:{},toast:''};render();return}if(b.dataset.action==='open-notice'){state.active=noticeItem().id;state.screen='detail';render();return}if(b.dataset.action==='back'){state.screen='list';state.tab=selected()?.kind==='update'?'updates':'pending';render();return}if(b.dataset.action==='comment'){let a=$('#comment-area');a.innerHTML=`<textarea class="comment" placeholder="Tulis komentar untuk tim..." rows="3"></textarea><button class="small-link" data-action="send-comment">Kirim komentar simulasi</button>`;return}if(b.dataset.action==='send-comment'){let v=$('.comment')?.value.trim();state.toast=v?'Komentar tersimpan dalam simulasi':'Tulis komentar dahulu';render();return}if(b.dataset.tab){state.tab=b.dataset.tab;render();return}if(b.dataset.open){state.active=b.dataset.open;state.screen='detail';render();return}if(b.dataset.respond){let x=selected();state.responses[x.id]=b.dataset.respond==='yes'?x.yes:x.no;render()}});
document.addEventListener('change',e=>{if(e.target.id==='property'){state.property=e.target.value;render()}});document.addEventListener('input',e=>{if(e.target.id==='search'){let pos=e.target.selectionStart;state.query=e.target.value;render();let input=$('#search');input.focus();input.setSelectionRange(pos,pos)}});
render();
